import Head from "next/head";
import { signIn, signOut, useSession } from 'next-auth/react'
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import { MantineProvider, Button, Checkbox } from "@mantine/core";
import Layout from "../components/layout.js";

export default function Home() {
    const { data: session } = useSession()
    console.log(process.env.GOOGLE_ID)
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MantineProvider theme={{ colorScheme: "dark" }}>
                <Layout />
            </MantineProvider>
            
            {!session && (
                <>
                    Not signed in <br />
                    <button onClick={() => signIn()}>Sign in</button>
                </>
            )}
            
            {session && <> 
                <h4>You are logged as: {session.user.name}</h4>
                <button className={styles.primaryButton} onClick={() => signOut()}>
                    Sign Out
                </button>
            </>}
        </div>
    );
}
