import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Checkbox } from "@mantine/core";
import Layout from "../components/layout.js";
import NashComponent from "../components/NashComponent.js";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NashComponent></NashComponent>
            <Layout />
        </div>
    );
}
